# Generated by Django 3.1.3 on 2020-11-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('employed_home', models.BooleanField(null=True)),
                ('employed_outside_of_home', models.BooleanField(null=True)),
                ('frontline_worker', models.BooleanField(null=True)),
                ('furloughed_unemployed', models.BooleanField(null=True)),
                ('retired', models.BooleanField(null=True)),
                ('student', models.BooleanField(null=True)),
                ('none_of_above', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=7)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('male', models.BooleanField(null=True)),
                ('female', models.BooleanField(null=True)),
                ('transgender_male', models.BooleanField(null=True)),
                ('transgender_female', models.BooleanField(null=True)),
                ('non_binary', models.BooleanField(null=True)),
                ('self_identify', models.BooleanField(null=True)),
                ('none_of_above', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('allergy_vaccine', models.BooleanField(null=True)),
                ('autoimmune_disease', models.BooleanField(null=True)),
                ('cancer', models.BooleanField(null=True)),
                ('immunocompromised', models.BooleanField(null=True)),
                ('diabetes', models.BooleanField(null=True)),
                ('heart_disease', models.BooleanField(null=True)),
                ('high_blood_pressure', models.BooleanField(null=True)),
                ('kidney_liver_disease', models.BooleanField(null=True)),
                ('lung_disease', models.BooleanField(null=True)),
                ('stroke', models.BooleanField(null=True)),
                ('another_serious_chronic_illness', models.BooleanField(null=True)),
                ('none_of_above', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='iCData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iCRepresentativeName', models.CharField(max_length=200)),
                ('iCLatestCallDate', models.DateField(null=True)),
                ('iCOptOut', models.CharField(max_length=200)),
                ('iCCallBackNeeded', models.CharField(max_length=200)),
                ('iCCallBackDateTime', models.DateTimeField(null=True)),
                ('iCReceivedOtherC19Vaccine', models.CharField(max_length=200)),
                ('iCComments', models.TextField()),
                ('iCInUseBy', models.CharField(max_length=200)),
                ('iCReadyforStudyTeam', models.CharField(max_length=200)),
                ('iCCreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('iCLastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceEthnicity',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('american_indian_alaska_native', models.BooleanField(null=True)),
                ('asian', models.BooleanField(null=True)),
                ('black_african_american', models.BooleanField(null=True)),
                ('hispanic_latino_spanish_origin', models.BooleanField(null=True)),
                ('hawaiian_pacific_islander', models.BooleanField(null=True)),
                ('white', models.BooleanField(null=True)),
                ('other_race_ethnicity', models.BooleanField(null=True)),
                ('none_of_above', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='studyTeamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyTeamOptOut', models.BooleanField(null=True)),
                ('studyTeamEligibilityOutcome', models.CharField(choices=[('EL', 'Eligible'), ('IE', 'Ineligible'), ('IO', 'Ineligible - opt out of all studies'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('studyTeamEnrollmentStatus', models.CharField(choices=[('EN', 'Enrolled'), ('EP', 'Enrollment pending'), ('NE', 'Not enrolled')], default='NE', max_length=18)),
                ('studyTeamComments', models.TextField()),
                ('studyTeamName', models.CharField(max_length=200)),
                ('studyTeamCreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('studyTeamLastModifiedDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('car', models.BooleanField(null=True)),
                ('carpool_or_vanpool', models.BooleanField(null=True)),
                ('frequent_air_travel', models.BooleanField(null=True)),
                ('public_transport', models.BooleanField(null=True)),
                ('walk_bike', models.BooleanField(null=True)),
                ('work_from_home', models.BooleanField(null=True)),
                ('none_of_above', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('veteran', models.BooleanField(null=True)),
                ('active_duty', models.BooleanField(null=True)),
                ('va_employee', models.BooleanField(null=True)),
                ('family_member_caregiver', models.BooleanField(null=True)),
                ('va_healthcare_champva', models.BooleanField(null=True)),
                ('national_guard_reserves', models.BooleanField(null=True)),
                ('none_of_above', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middle', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('suffix', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('zipCode', models.CharField(max_length=5)),
                ('veteranDateOfBirth', models.DateField()),
                ('GENDER_SELF_IDENTIFY_DETAILS', models.CharField(max_length=200)),
                ('diagnosed', models.CharField(max_length=200)),
                ('closeContactPositive', models.CharField(max_length=200)),
                ('hospitalized', models.CharField(max_length=200)),
                ('smokeOrVape', models.CharField(max_length=200)),
                ('residentsInHome', models.CharField(max_length=200)),
                ('closeContact', models.CharField(max_length=200)),
                ('consentAgreementAccepted', models.CharField(max_length=200)),
                ('formData', models.JSONField()),
                ('registrantDataLastModifiedDateTime', models.DateTimeField(auto_now=True)),
                ('registrantDataCreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('EMPLOYMENT_STATUS', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocketship.employmentstatus')),
                ('GENDER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocketship.gender')),
                ('HEALTH_HISTORY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocketship.healthhistory')),
                ('RACE_ETHNICITY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocketship.raceethnicity')),
                ('TRANSPORTATION', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocketship.transportation')),
                ('VETERAN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocketship.veteran')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionId', models.SlugField(max_length=200, unique=True)),
                ('recordCreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('recordLastModifiedDateTime', models.DateTimeField(auto_now=True)),
                ('iCData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocketship.icdata')),
                ('registrantData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocketship.registrantdata')),
                ('studyTeamData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocketship.studyteamdata')),
            ],
        ),
    ]
